export type BrainstormSeed = {
  number: number;
  bucket: 'EDUCATE' | 'RELATE' | 'INSPIRE' | 'SELL';
  sub_category: string;
  text: string;
};

export const QUESTIONS: BrainstormSeed[] = [
  // EDUCATE - Problem Awareness
  { number: 1, bucket: 'EDUCATE', sub_category: 'Problem Awareness', text: "What's the biggest challenge for beginners who are just starting out in your niche?" },
  { number: 2, bucket: 'EDUCATE', sub_category: 'Problem Awareness', text: "What tasks do your ideal clients CONSTANTLY procrastinate? Why?" },
  { number: 3, bucket: 'EDUCATE', sub_category: 'Problem Awareness', text: "What feels hard for your audience on a daily basis?" },
  { number: 4, bucket: 'EDUCATE', sub_category: 'Problem Awareness', text: "What is taking up a ton of time for your audience? How do they feel they're wasting their time?" },
  { number: 5, bucket: 'EDUCATE', sub_category: 'Problem Awareness', text: "How does your audience feel stuck? What do they think is keeping them stuck? What do they not yet realize is keeping them stuck?" },
  { number: 6, bucket: 'EDUCATE', sub_category: 'Problem Awareness', text: "What do you immediately flag as a problem, that they haven't realized is a problem yet?" },
  { number: 7, bucket: 'EDUCATE', sub_category: 'Problem Awareness', text: "What's a big mistake you see others in your profession making and/or teaching in your industry?" },
  { number: 8, bucket: 'EDUCATE', sub_category: 'Problem Awareness', text: "How are your people holding themselves back? What are they telling themselves that isn't true? What have they been told that isn't true?" },
  { number: 9, bucket: 'EDUCATE', sub_category: 'Problem Awareness', text: "How does your audience feel they're failing or flailing? What easy-to-grab successes do you see that are possible for them?" },
  { number: 10, bucket: 'EDUCATE', sub_category: 'Problem Awareness', text: "What has your audience tried before that hasn't worked? Why didn't it work?" },
  { number: 11, bucket: 'EDUCATE', sub_category: 'Problem Awareness', text: "When people see your offer and think, \"I COULD buy that, or I could just…\" how do they finish that sentence?" },
  { number: 12, bucket: 'EDUCATE', sub_category: 'Problem Awareness', text: "What mistakes do people often make when trying to DIY/solve problems without your product/service?" },
  { number: 13, bucket: 'EDUCATE', sub_category: 'Problem Awareness', text: "What's the most common mistake people make before they hire you/buy from you? What are the consequences?" },
  { number: 14, bucket: 'EDUCATE', sub_category: 'Problem Awareness', text: "Why does it make sense that people haven't solved the problem yet?" },
  { number: 15, bucket: 'EDUCATE', sub_category: 'Problem Awareness', text: "What common questions do people find themselves asking? What questions do you get in your DMs?" },

  // EDUCATE - Actionable Tips
  { number: 16, bucket: 'EDUCATE', sub_category: 'Actionable Tips', text: "Take a specific problem your audience is facing: what are 3-8 general steps you would take to solve it? Pick one of those steps and teach it." },
  { number: 17, bucket: 'EDUCATE', sub_category: 'Actionable Tips', text: "If you're at master level in solving this problem, what does the novice level look like? Show them how to do what you do at novice level." },
  { number: 18, bucket: 'EDUCATE', sub_category: 'Actionable Tips', text: "What is your audience DIY-ing? For each task, how can you help them DIY faster or more successfully?" },
  { number: 19, bucket: 'EDUCATE', sub_category: 'Actionable Tips', text: "Take a specific problem: What's a hack or workaround you discovered that would make it easier? Share exactly how to do it." },
  { number: 20, bucket: 'EDUCATE', sub_category: 'Actionable Tips', text: "Where is your audience wasting time? What are simple ways they can be more efficient?" },
  { number: 21, bucket: 'EDUCATE', sub_category: 'Actionable Tips', text: "What is your audience wasting energy trying to do or fix? What should they do instead?" },
  { number: 22, bucket: 'EDUCATE', sub_category: 'Actionable Tips', text: "What tasks/actions are taking them more time and effort than is necessary? What should they do instead?" },
  { number: 23, bucket: 'EDUCATE', sub_category: 'Actionable Tips', text: "What is your audience currently doing wrong? In what ways are they contributing to their own poor results?" },
  { number: 24, bucket: 'EDUCATE', sub_category: 'Actionable Tips', text: "What do they think will be difficult that can actually be simple or straightforward?" },
  { number: 25, bucket: 'EDUCATE', sub_category: 'Actionable Tips', text: "What would you teach your ideal clients if they were paying you $10,000 for 5 minutes of your time? The basic essentials." },
  { number: 26, bucket: 'EDUCATE', sub_category: 'Actionable Tips', text: "Take a specific task you do every day, break it into smaller tasks, then a detailed how-to." },
  { number: 27, bucket: 'EDUCATE', sub_category: 'Actionable Tips', text: "What would you recommend to someone who can't afford to spend any money? What can they do themselves in the meantime?" },
  { number: 28, bucket: 'EDUCATE', sub_category: 'Actionable Tips', text: "If someone only has $10 to spend, what should they spend it on? What about $100? What about $1000?" },
  { number: 29, bucket: 'EDUCATE', sub_category: 'Actionable Tips', text: "What's ONE part of a how-to that you could explain deeper? Turn it into a step-by-step breakdown or video tutorial." },

  // EDUCATE - Value Shares
  { number: 30, bucket: 'EDUCATE', sub_category: 'Value Shares', text: "What do you commonly see people doing incorrectly? What is a better way to do it?" },
  { number: 31, bucket: 'EDUCATE', sub_category: 'Value Shares', text: "What is a task people make more complicated than it needs to be? What's a simpler way?" },
  { number: 32, bucket: 'EDUCATE', sub_category: 'Value Shares', text: "Imagine you're talking to someone COMPLETELY new to your industry. How can they tell what's valuable advice and what's not?" },
  { number: 33, bucket: 'EDUCATE', sub_category: 'Value Shares', text: "What are some of the more complex concepts in your industry? How can you break them down into super easy terms?" },
  { number: 34, bucket: 'EDUCATE', sub_category: 'Value Shares', text: "What do most people THINK they have to do to solve their problems, but you know is really not true?" },
  { number: 35, bucket: 'EDUCATE', sub_category: 'Value Shares', text: "What \"uncomfortable\" truth or topic can you address/call out?" },
  { number: 36, bucket: 'EDUCATE', sub_category: 'Value Shares', text: "What are the questions you most often get from people about your business or industry?" },
  { number: 37, bucket: 'EDUCATE', sub_category: 'Value Shares', text: "What options or alternatives might people have trouble deciding between?" },
  { number: 38, bucket: 'EDUCATE', sub_category: 'Value Shares', text: "What do people get wrong about the work you do? What do you wish they knew?" },
  { number: 39, bucket: 'EDUCATE', sub_category: 'Value Shares', text: "What bad advice do other people in your industry give? Why is it bad? What advice would YOU give?" },
  { number: 40, bucket: 'EDUCATE', sub_category: 'Value Shares', text: "What advice do you hear in your industry that's only PARTIALLY true or only true SOMETIMES? What are the exceptions?" },
  { number: 41, bucket: 'EDUCATE', sub_category: 'Value Shares', text: "What is an important task or topic people commonly skip over or don't realize is so important?" },

  // EDUCATE - Plug-and-Play
  { number: 42, bucket: 'EDUCATE', sub_category: 'Plug-and-Play', text: "What tasks is your audience doing daily? Break each down. Is there anything you can give them to knock one off their list?" },
  { number: 43, bucket: 'EDUCATE', sub_category: 'Plug-and-Play', text: "What's something you use in your business every single day? What would be on a List of Essentials for your audience?" },
  { number: 44, bucket: 'EDUCATE', sub_category: 'Plug-and-Play', text: "Take a specific problem: What are at least 5 products or practices useful in solving it? What is each useful for?" },
  { number: 45, bucket: 'EDUCATE', sub_category: 'Plug-and-Play', text: "What can you give your people they'd use every day? Every week? Every month? Every year?" },
  { number: 46, bucket: 'EDUCATE', sub_category: 'Plug-and-Play', text: "What's something in your work that you can think of 20 ideas for? 101? 365?" },
  { number: 47, bucket: 'EDUCATE', sub_category: 'Plug-and-Play', text: "What's something you've created or used in your business that you can share with your audience?" },
  { number: 48, bucket: 'EDUCATE', sub_category: 'Plug-and-Play', text: "What different archetypes, identities, experience levels, or interests does your audience have? What might you make for each?" },

  // EDUCATE - Expert Showcase
  { number: 49, bucket: 'EDUCATE', sub_category: 'Expert Showcase', text: "If you were teaching a substitute how to complete a task for you, what guide would you give them?" },
  { number: 50, bucket: 'EDUCATE', sub_category: 'Expert Showcase', text: "Take a how-to post and add your own examples to show it in practice." },
  { number: 51, bucket: 'EDUCATE', sub_category: 'Expert Showcase', text: "Take a project you've worked on: how did you do what you did? Why did you make the choices you made?" },
  { number: 52, bucket: 'EDUCATE', sub_category: 'Expert Showcase', text: "Take a service you offer: what's something SUPER valuable you do during this service? Why is it valuable?" },
  { number: 53, bucket: 'EDUCATE', sub_category: 'Expert Showcase', text: "Take a product you offer: what's something SUPER valuable about it? Why? How did you make it?" },
  { number: 54, bucket: 'EDUCATE', sub_category: 'Expert Showcase', text: "Take a project someone else in your industry has done and break down the strategy as an expert." },
  { number: 55, bucket: 'EDUCATE', sub_category: 'Expert Showcase', text: "Take a project someone else has done and play critic: what's working and what you would have done differently?" },
  { number: 56, bucket: 'EDUCATE', sub_category: 'Expert Showcase', text: "What common task do you do better than most other people? Show examples of the common way vs your way." },
  { number: 57, bucket: 'EDUCATE', sub_category: 'Expert Showcase', text: "Show how you complete a complex, complicated, or intimidating task. Simplify how it's done." },
  { number: 58, bucket: 'EDUCATE', sub_category: 'Expert Showcase', text: "Reflect on a big task you've completed. Outline all the steps you took." },
  { number: 59, bucket: 'EDUCATE', sub_category: 'Expert Showcase', text: "Reflect on a small task you've completed. Outline all the steps you took to do it remarkably well." },
  { number: 60, bucket: 'EDUCATE', sub_category: 'Expert Showcase', text: "Consider what the standard is for completed work in your industry. In what ways do you go above and beyond?" },

  // EDUCATE - Business Insider
  { number: 61, bucket: 'EDUCATE', sub_category: 'Business Insider', text: "What goals have you reached in your business so far? What were the main things you did to achieve each one?" },
  { number: 62, bucket: 'EDUCATE', sub_category: 'Business Insider', text: "What limitations do you work with (time, staff, experience)? How have you worked around them?" },
  { number: 63, bucket: 'EDUCATE', sub_category: 'Business Insider', text: "What business advice do you outright ignore? Is there anything you intentionally do differently?" },
  { number: 64, bucket: 'EDUCATE', sub_category: 'Business Insider', text: "What questions do you ask new clients/vendors/collaborators? What are you looking to align on?" },
  { number: 65, bucket: 'EDUCATE', sub_category: 'Business Insider', text: "What does the backend of your business OR your client process look like? Why did you set it up like that?" },
  { number: 66, bucket: 'EDUCATE', sub_category: 'Business Insider', text: "What automations or processes do you embrace to help your business run smoothly?" },
  { number: 67, bucket: 'EDUCATE', sub_category: 'Business Insider', text: "What do you invest in as a business owner? Why is it valuable? How do you know it's worth it?" },
  { number: 68, bucket: 'EDUCATE', sub_category: 'Business Insider', text: "What tasks/processes do you do proactively to set yourself up for success?" },
  { number: 69, bucket: 'EDUCATE', sub_category: 'Business Insider', text: "What projects and products are you currently working on? What are you planning for in the future?" },
  { number: 70, bucket: 'EDUCATE', sub_category: 'Business Insider', text: "What mistakes have you made in your business? What would you do differently?" },
  { number: 71, bucket: 'EDUCATE', sub_category: 'Business Insider', text: "What investments have you made that were not worth it?" },
  { number: 72, bucket: 'EDUCATE', sub_category: 'Business Insider', text: "What did you wait to do or invest in that you should have done sooner?" },

  // RELATE - Personal Introductions
  { number: 73, bucket: 'RELATE', sub_category: 'Personal Introductions', text: "What's your story? How did you start doing this work?" },
  { number: 74, bucket: 'RELATE', sub_category: 'Personal Introductions', text: "What are some of the most surprising stories or facts about you?" },
  { number: 75, bucket: 'RELATE', sub_category: 'Personal Introductions', text: "What are 5-10 fun things everyone should know about you?" },
  { number: 76, bucket: 'RELATE', sub_category: 'Personal Introductions', text: "What story would your best friends tell about you if they had to describe you in one story?" },
  { number: 77, bucket: 'RELATE', sub_category: 'Personal Introductions', text: "What are 3-5 things you do EVERY SINGLE DAY?" },
  { number: 78, bucket: 'RELATE', sub_category: 'Personal Introductions', text: "[Reel] Introduce yourself and show how you do something you're especially good at." },
  { number: 79, bucket: 'RELATE', sub_category: 'Personal Introductions', text: "Describe the moment you decided to start your business. The aha moment. Why do you do what you do?" },
  { number: 80, bucket: 'RELATE', sub_category: 'Personal Introductions', text: "Name all the roles you play in your life (entrepreneur, ops manager, procrastinator, reality TV addict)." },
  { number: 81, bucket: 'RELATE', sub_category: 'Personal Introductions', text: "Hypothetical situation: what role would you and your team take?" },
  { number: 82, bucket: 'RELATE', sub_category: 'Personal Introductions', text: "Which TV show character would each of you most likely be?" },
  { number: 83, bucket: 'RELATE', sub_category: 'Personal Introductions', text: "What would each person's nickname be related to their special skill?" },
  { number: 84, bucket: 'RELATE', sub_category: 'Personal Introductions', text: "Describe the type of people you would REALLY love to work with. Why them?" },
  { number: 85, bucket: 'RELATE', sub_category: 'Personal Introductions', text: "What are the non-negotiable things you and your ideal clients need to align on?" },
  { number: 86, bucket: 'RELATE', sub_category: 'Personal Introductions', text: "What kind of non-red-flag client are you totally wrong for?" },
  { number: 87, bucket: 'RELATE', sub_category: 'Personal Introductions', text: "Share your company values. What do you believe in and how do you practice them in real time?" },
  { number: 88, bucket: 'RELATE', sub_category: 'Personal Introductions', text: "Does your business donate to any charitable organizations? Which ones, and why?" },
  { number: 89, bucket: 'RELATE', sub_category: 'Personal Introductions', text: "What about your job or business brings you the most joy? What are you especially excellent at?" },

  // RELATE - Story Shares
  { number: 90, bucket: 'RELATE', sub_category: 'Story Shares', text: "What are 5 moments in your business where you thought \"I don't think I can do this.\" SHOW each. How did you get through?" },
  { number: 91, bucket: 'RELATE', sub_category: 'Story Shares', text: "What was a moment in your business where you TRULY doubted yourself? How did you get past it?" },
  { number: 92, bucket: 'RELATE', sub_category: 'Story Shares', text: "A moment when you worked REALLY hard for something and it didn't pay off. Tell the whole story. What did you learn?" },
  { number: 93, bucket: 'RELATE', sub_category: 'Story Shares', text: "Ever made a bad investment? Tell the whole story. What valuable info can you share?" },
  { number: 94, bucket: 'RELATE', sub_category: 'Story Shares', text: "Last time you felt SUPER stressed out. What led up to it? What did you learn?" },
  { number: 95, bucket: 'RELATE', sub_category: 'Story Shares', text: "Story of a time you disappointed a client. What did they say? How did you respond? What did you learn?" },
  { number: 96, bucket: 'RELATE', sub_category: 'Story Shares', text: "Time when you were unprepared, underprepared, or in over your head. What happened honestly?" },
  { number: 97, bucket: 'RELATE', sub_category: 'Story Shares', text: "What changes have you made over your business? What have you intentionally stopped/started?" },
  { number: 98, bucket: 'RELATE', sub_category: 'Story Shares', text: "Describe a BIG WIN moment. What was it? How did you celebrate? What challenging moments led to it?" },
  { number: 99, bucket: 'RELATE', sub_category: 'Story Shares', text: "When do you feel like a \"bad\" business owner? When was being a \"bad\" business owner the right choice?" },
  { number: 100, bucket: 'RELATE', sub_category: 'Story Shares', text: "When do you feel like a \"good\" business owner? When was being a \"good\" business owner the wrong choice?" },
  { number: 101, bucket: 'RELATE', sub_category: 'Story Shares', text: "What change in your business has been the most difficult to make? What were the results?" },
  { number: 102, bucket: 'RELATE', sub_category: 'Story Shares', text: "What change have you been the most resistant to?" },
  { number: 103, bucket: 'RELATE', sub_category: 'Story Shares', text: "What lesson in business took you the longest to learn? When did you finally have the aha moment?" },
  { number: 104, bucket: 'RELATE', sub_category: 'Story Shares', text: "How did your life look the moment you decided to start your business? 1 month later? 1 year? 5 years?" },
  { number: 105, bucket: 'RELATE', sub_category: 'Story Shares', text: "What moments in your journey stand out as crossroads, turning points, or climactic events?" },
  { number: 106, bucket: 'RELATE', sub_category: 'Story Shares', text: "What are 3 stories you will always remember from your entrepreneurship journey?" },
  { number: 107, bucket: 'RELATE', sub_category: 'Story Shares', text: "What moments in your clients' journey stand out? Biggest wins and losses they've experienced?" },

  // RELATE - Behind The Scenes
  { number: 108, bucket: 'RELATE', sub_category: 'Behind The Scenes', text: "What does your day-to-day life look like in your job? Average tasks? How do you complete them?" },
  { number: 109, bucket: 'RELATE', sub_category: 'Behind The Scenes', text: "How do you start each workday? Do you have any habits or routines?" },
  { number: 110, bucket: 'RELATE', sub_category: 'Behind The Scenes', text: "What tools or programs do you use to keep your business running?" },
  { number: 111, bucket: 'RELATE', sub_category: 'Behind The Scenes', text: "What task or part of your workday are you always MOST excited for?" },
  { number: 112, bucket: 'RELATE', sub_category: 'Behind The Scenes', text: "What task or part of your workday are you always LEAST excited for?" },
  { number: 113, bucket: 'RELATE', sub_category: 'Behind The Scenes', text: "Activities/events you do weekly, monthly, yearly, once in a blue moon?" },
  { number: 114, bucket: 'RELATE', sub_category: 'Behind The Scenes', text: "How do you prepare for once-in-a-blue-moon activities or events in your business?" },
  { number: 115, bucket: 'RELATE', sub_category: 'Behind The Scenes', text: "How many hours a day do you work? How do you know when to quit? What do you do to decompress?" },
  { number: 116, bucket: 'RELATE', sub_category: 'Behind The Scenes', text: "How do you keep work life separate from personal life when working from home?" },
  { number: 117, bucket: 'RELATE', sub_category: 'Behind The Scenes', text: "What does your workspace setup look like?" },
  { number: 118, bucket: 'RELATE', sub_category: 'Behind The Scenes', text: "What is your FAVORITE thing in your office? Why? How does it improve your work life?" },
  { number: 119, bucket: 'RELATE', sub_category: 'Behind The Scenes', text: "What have you been working on behind-the-scenes that you have yet to release publicly?" },
  { number: 120, bucket: 'RELATE', sub_category: 'Behind The Scenes', text: "What roadblocks are you facing or working through in your business right now?" },
  { number: 121, bucket: 'RELATE', sub_category: 'Behind The Scenes', text: "How did you plan for your latest launch? Timeline? What did you create?" },

  // RELATE - Engagement Invitations
  { number: 122, bucket: 'RELATE', sub_category: 'Engagement Invitations', text: "Ask your audience to comment their favorite books/podcasts/accounts/advice related to your industry." },
  { number: 123, bucket: 'RELATE', sub_category: 'Engagement Invitations', text: "Ask audience to self-identify from a variety of options (attachment style vs color scheme)." },
  { number: 124, bucket: 'RELATE', sub_category: 'Engagement Invitations', text: "Create a mock-up of 3 versions of a product/service. Invite audience to vote." },
  { number: 125, bucket: 'RELATE', sub_category: 'Engagement Invitations', text: "Share a meme dump related to a problem in your industry. Ask which one they most relate to." },
  { number: 126, bucket: 'RELATE', sub_category: 'Engagement Invitations', text: "Ask audience to choose a name for your upcoming product. Give 3 options or invite ideas." },
  { number: 127, bucket: 'RELATE', sub_category: 'Engagement Invitations', text: "Ask your people directly: What do they want to see next? What do they need help with?" },
  { number: 128, bucket: 'RELATE', sub_category: 'Engagement Invitations', text: "Invite audience to play \"Can you [do this better]?\" with a prompt from your industry." },
  { number: 129, bucket: 'RELATE', sub_category: 'Engagement Invitations', text: "Surprising or confusing photo - start a best comment contest." },
  { number: 130, bucket: 'RELATE', sub_category: 'Engagement Invitations', text: "What could you have people guess or estimate about your work or business?" },
  { number: 131, bucket: 'RELATE', sub_category: 'Engagement Invitations', text: "What are some activities related to your product or work?" },
  { number: 132, bucket: 'RELATE', sub_category: 'Engagement Invitations', text: "What are ways you can measure progress or a starting point towards a goal?" },

  // RELATE - Reflections & Recaps
  { number: 133, bucket: 'RELATE', sub_category: 'Reflections & Recaps', text: "What's something new you're trying right now that IS working? Share results, reflect on the change." },
  { number: 134, bucket: 'RELATE', sub_category: 'Reflections & Recaps', text: "What's a challenge you're working through RIGHT NOW? What's hard about it?" },
  { number: 135, bucket: 'RELATE', sub_category: 'Reflections & Recaps', text: "Something new you're trying that is NOT working? Why? What would you iterate?" },
  { number: 136, bucket: 'RELATE', sub_category: 'Reflections & Recaps', text: "What is a new project you're JUST starting to work on? How are you approaching it?" },
  { number: 137, bucket: 'RELATE', sub_category: 'Reflections & Recaps', text: "Recap last month/quarter/year. Where did revenue come from? Best seller? Top reviewed?" },
  { number: 138, bucket: 'RELATE', sub_category: 'Reflections & Recaps', text: "Recap your last launch. What did you make? Where did revenue come from? What will you repeat/change?" },
  { number: 139, bucket: 'RELATE', sub_category: 'Reflections & Recaps', text: "Reflect when you reach milestones (X years, X followers, $X earned). What got you there?" },
  { number: 140, bucket: 'RELATE', sub_category: 'Reflections & Recaps', text: "What does your business budget look like? Your profitability?" },
  { number: 141, bucket: 'RELATE', sub_category: 'Reflections & Recaps', text: "What's the best feedback you received this past month? What did it mean to you?" },
  { number: 142, bucket: 'RELATE', sub_category: 'Reflections & Recaps', text: "What negative feedback can you have a sense of humor about?" },
  { number: 143, bucket: 'RELATE', sub_category: 'Reflections & Recaps', text: "What do you do \"wrong\" by other people's standards but \"right\" by yours?" },

  // RELATE - Just for Fun
  { number: 144, bucket: 'RELATE', sub_category: 'Just for Fun', text: "What are your favorite things to do apart from your business? How do your hobbies influence your work?" },
  { number: 145, bucket: 'RELATE', sub_category: 'Just for Fun', text: "What's something new you're learning? How does it feel to be a beginner again?" },
  { number: 146, bucket: 'RELATE', sub_category: 'Just for Fun', text: "How is your business celebrating the holidays?" },
  { number: 147, bucket: 'RELATE', sub_category: 'Just for Fun', text: "What are you/friends/family obsessed with lately? Look at it through the lens of your business." },
  { number: 148, bucket: 'RELATE', sub_category: 'Just for Fun', text: "Play with sarcasm. Create a how-to post full of sarcastic advice." },
  { number: 149, bucket: 'RELATE', sub_category: 'Just for Fun', text: "Do you have kids or pets? How are they involved in your business?" },
  { number: 150, bucket: 'RELATE', sub_category: 'Just for Fun', text: "Throwback post: who were you as a pre-teen? Trends you followed? Connect to who you are now." },
  { number: 151, bucket: 'RELATE', sub_category: 'Just for Fun', text: "Post something related to your business that makes you laugh." },

  // INSPIRE - Case Studies
  { number: 152, bucket: 'INSPIRE', sub_category: 'Case Studies', text: "Something you used to do that you've now STOPPED doing? Results of this change? Make them quantifiable." },
  { number: 153, bucket: 'INSPIRE', sub_category: 'Case Studies', text: "Time you took feedback from a client: what did you change? What was the result?" },
  { number: 154, bucket: 'INSPIRE', sub_category: 'Case Studies', text: "What transformations do your clients mention when they talk about your product/service?" },
  { number: 155, bucket: 'INSPIRE', sub_category: 'Case Studies', text: "What can you measure about these transformations? Revenue, sales, conversion, followers, engagement, DMs, time spent?" },
  { number: 156, bucket: 'INSPIRE', sub_category: 'Case Studies', text: "How did their personal experience change? How can you make it quantifiable (1-10 pain scale)?" },

  // INSPIRE - Struggle Share
  { number: 157, bucket: 'INSPIRE', sub_category: 'Struggle Share', text: "What did your client tell you they were struggling with before working with you? Exact words." },
  { number: 158, bucket: 'INSPIRE', sub_category: 'Struggle Share', text: "What emotional hesitations did they have? What had they tried? When did they almost give up?" },
  { number: 159, bucket: 'INSPIRE', sub_category: 'Struggle Share', text: "What financial hesitations did they have? Why did they think it was too expensive?" },
  { number: 160, bucket: 'INSPIRE', sub_category: 'Struggle Share', text: "How can you put each hesitation at ease? Which are valid, which are based on anxiety?" },
  { number: 161, bucket: 'INSPIRE', sub_category: 'Struggle Share', text: "What made them get past these hesitations?" },
  { number: 162, bucket: 'INSPIRE', sub_category: 'Struggle Share', text: "How did it feel when they finally decided to work with you? What were they hopeful for?" },
  { number: 163, bucket: 'INSPIRE', sub_category: 'Struggle Share', text: "Were there difficult points along the journey? How did they get through them?" },
  { number: 164, bucket: 'INSPIRE', sub_category: 'Struggle Share', text: "What do they think of the result? What hesitations did it put to rest?" },
  { number: 165, bucket: 'INSPIRE', sub_category: 'Struggle Share', text: "What would they have missed out on if they'd skipped your solution?" },

  // INSPIRE - Turning Point
  { number: 166, bucket: 'INSPIRE', sub_category: 'Turning Point', text: "What have people done to try to solve their problem in the past? Why didn't it work?" },
  { number: 167, bucket: 'INSPIRE', sub_category: 'Turning Point', text: "What misconceptions do your clients have before working with you? Give an example that challenges it." },
  { number: 168, bucket: 'INSPIRE', sub_category: 'Turning Point', text: "For your target audience: in what ways do other solutions fall short?" },
  { number: 169, bucket: 'INSPIRE', sub_category: 'Turning Point', text: "What misconceptions did YOU have about your work before you went into it? What changed YOUR mind?" },
  { number: 170, bucket: 'INSPIRE', sub_category: 'Turning Point', text: "Why does it make sense that other solutions haven't worked? How have they been misled?" },
  { number: 171, bucket: 'INSPIRE', sub_category: 'Turning Point', text: "What mindset shifts do your people need to make? What do they need to let go of?" },

  // INSPIRE - Before & After
  { number: 172, bucket: 'INSPIRE', sub_category: 'Before & After', text: "Compare a first draft or initial sketch with the final product you deliver." },
  { number: 173, bucket: 'INSPIRE', sub_category: 'Before & After', text: "What visually changed for your client before and after using your product/service?" },
  { number: 174, bucket: 'INSPIRE', sub_category: 'Before & After', text: "How did your client feel before vs after?" },
  { number: 175, bucket: 'INSPIRE', sub_category: 'Before & After', text: "What was your client's mental state before and after? Thoughts? Worries? Future they saw?" },
  { number: 176, bucket: 'INSPIRE', sub_category: 'Before & After', text: "What was your client's financial situation before and after?" },
  { number: 177, bucket: 'INSPIRE', sub_category: 'Before & After', text: "Story of what your client's experience looked like BEFORE working with you." },
  { number: 178, bucket: 'INSPIRE', sub_category: 'Before & After', text: "Story of your client's experience AFTER working with you." },
  { number: 179, bucket: 'INSPIRE', sub_category: 'Before & After', text: "What are 3 different ways you could show the difference before vs after? (photos, charts, quotes, timelines)" },
  { number: 180, bucket: 'INSPIRE', sub_category: 'Before & After', text: "What did the transformation look like while it was happening? What major decisions were made?" },
  { number: 181, bucket: 'INSPIRE', sub_category: 'Before & After', text: "Did you come to any crossroads or big questions on your way from A to B?" },
  { number: 182, bucket: 'INSPIRE', sub_category: 'Before & After', text: "What difficult work or consistent action was required to make the transformation happen?" },

  // INSPIRE - Visualizations and Projections
  { number: 183, bucket: 'INSPIRE', sub_category: 'Visualizations and Projections', text: "How would your client's life look different in 1 month if they got your product/service now? 6 months? 1 year?" },
  { number: 184, bucket: 'INSPIRE', sub_category: 'Visualizations and Projections', text: "What would their life look like if they chose NOT to invest now? What problems would they STILL have?" },
  { number: 185, bucket: 'INSPIRE', sub_category: 'Visualizations and Projections', text: "What growth/success/happiness/relief can they look forward to? Can you quantify it?" },
  { number: 186, bucket: 'INSPIRE', sub_category: 'Visualizations and Projections', text: "Take a current client's results and project how they'll get even better in 1 month, 6 months, 1 year." },
  { number: 187, bucket: 'INSPIRE', sub_category: 'Visualizations and Projections', text: "What would your clients be able to spend more time on later if they invested now?" },
  { number: 188, bucket: 'INSPIRE', sub_category: 'Visualizations and Projections', text: "How would the investment pay off? How long would it take to make back?" },
  { number: 189, bucket: 'INSPIRE', sub_category: 'Visualizations and Projections', text: "Visualize different scenarios where a client could make back their investment in 1, 3, 6, 12 months." },
  { number: 190, bucket: 'INSPIRE', sub_category: 'Visualizations and Projections', text: "What are 3 VERY possible ways clients could make back their investment in 6 months?" },
  { number: 191, bucket: 'INSPIRE', sub_category: 'Visualizations and Projections', text: "Who is this realistic for? What do clients need to have figured out to be a good match?" },

  // INSPIRE - Portfolio Shares
  { number: 192, bucket: 'INSPIRE', sub_category: 'Portfolio Shares', text: "Product or project you LOVED working on that shows off your expertise. What about it do you love?" },
  { number: 193, bucket: 'INSPIRE', sub_category: 'Portfolio Shares', text: "Project made specifically for one client. Explain how it was made with them in mind." },
  { number: 194, bucket: 'INSPIRE', sub_category: 'Portfolio Shares', text: "Detail/element of a project you're especially proud of?" },
  { number: 195, bucket: 'INSPIRE', sub_category: 'Portfolio Shares', text: "Detail/element that took a long time to perfect? First, second, third drafts to final?" },
  { number: 196, bucket: 'INSPIRE', sub_category: 'Portfolio Shares', text: "Specific detail of a project a client especially LOVED? What did they say?" },
  { number: 197, bucket: 'INSPIRE', sub_category: 'Portfolio Shares', text: "Take a specific detail from a project and share the inspiration." },
  { number: 198, bucket: 'INSPIRE', sub_category: 'Portfolio Shares', text: "Take an element that's especially meaningful. How did you come up with the idea?" },
  { number: 199, bucket: 'INSPIRE', sub_category: 'Portfolio Shares', text: "All details of a project vs the big picture? How do they come together?" },
  { number: 200, bucket: 'INSPIRE', sub_category: 'Portfolio Shares', text: "Overview of everything you deliver. Tangible and intangible deliverables." },
  { number: 201, bucket: 'INSPIRE', sub_category: 'Portfolio Shares', text: "For each deliverable: everything that goes into creating and getting it to clients. Special moments." },
  { number: 202, bucket: 'INSPIRE', sub_category: 'Portfolio Shares', text: "How do you deliver your deliverables? If you have packaging, what's special about it?" },

  // SELL - Offer Pitch
  { number: 203, bucket: 'SELL', sub_category: 'Offer Pitch', text: "Take one specific offer. How is it the PERFECT solution for one problem or desire?" },
  { number: 204, bucket: 'SELL', sub_category: 'Offer Pitch', text: "When they buy your offer, what is immediately going to change for them?" },
  { number: 205, bucket: 'SELL', sub_category: 'Offer Pitch', text: "What will change for them in 6 months?" },
  { number: 206, bucket: 'SELL', sub_category: 'Offer Pitch', text: "What will change for them in 1 year?" },
  { number: 207, bucket: 'SELL', sub_category: 'Offer Pitch', text: "What's included in your offer, and what is the purpose of each inclusion?" },
  { number: 208, bucket: 'SELL', sub_category: 'Offer Pitch', text: "What proof do you have that your offer will help/be valuable?" },
  { number: 209, bucket: 'SELL', sub_category: 'Offer Pitch', text: "What's one specific part of your offer that is MAJORLY valuable? Deep dive that part." },
  { number: 210, bucket: 'SELL', sub_category: 'Offer Pitch', text: "Why should your audience buy your solution NOW and not in 6 months?" },

  // SELL - The Only Option
  { number: 211, bucket: 'SELL', sub_category: 'The Only Option', text: "What are competitors offering that you're decidedly NOT offering, and why?" },
  { number: 212, bucket: 'SELL', sub_category: 'The Only Option', text: "How does your product differ from current trends? Why aren't you following? How is yours better?" },
  { number: 213, bucket: 'SELL', sub_category: 'The Only Option', text: "What offers are similar to yours? What does your offer include that others don't?" },
  { number: 214, bucket: 'SELL', sub_category: 'The Only Option', text: "What does your offer do better than your competitors?" },
  { number: 215, bucket: 'SELL', sub_category: 'The Only Option', text: "If clients bought yours AND a similar offer, what would they say was special about yours?" },
  { number: 216, bucket: 'SELL', sub_category: 'The Only Option', text: "What makes your offer the ONLY choice?" },
  { number: 217, bucket: 'SELL', sub_category: 'The Only Option', text: "What return on investment can people expect? What proof do you have?" },
  { number: 218, bucket: 'SELL', sub_category: 'The Only Option', text: "What could they keep doing instead of buying your offer? Why is that the wrong choice?" },
  { number: 219, bucket: 'SELL', sub_category: 'The Only Option', text: "What potential pain or problems will they avoid by buying your offer?" },

  // SELL - Self-Selection
  { number: 220, bucket: 'SELL', sub_category: 'Self-Selection', text: "Who is your offer perfect for? Who should be RUNNING to checkout?" },
  { number: 221, bucket: 'SELL', sub_category: 'Self-Selection', text: "What day-to-day problems does your offer address? Think of 4-6 specific problems." },
  { number: 222, bucket: 'SELL', sub_category: 'Self-Selection', text: "How can people know this offer is right for them? Experience? Struggle? Hopes?" },
  { number: 223, bucket: 'SELL', sub_category: 'Self-Selection', text: "How does the person experiencing the big problem describe it to friends? In 10 words or less." },
  { number: 224, bucket: 'SELL', sub_category: 'Self-Selection', text: "What do your people wish they had more time for?" },
  { number: 225, bucket: 'SELL', sub_category: 'Self-Selection', text: "What limitations might people be working with that would still make them a good candidate?" },

  // SELL - Sliding Door Stories
  { number: 226, bucket: 'SELL', sub_category: 'Sliding Door Stories', text: "What did clients try before yours that didn't work? Why? How were they in a worse position after?" },
  { number: 227, bucket: 'SELL', sub_category: 'Sliding Door Stories', text: "What other potential \"solutions\" have YOU tried that failed? How were you worse off?" },
  { number: 228, bucket: 'SELL', sub_category: 'Sliding Door Stories', text: "Time you didn't invest in something and later regretted putting it off. What could you have avoided?" },

  // SELL - Excitement Builders & Lead Generators
  { number: 229, bucket: 'SELL', sub_category: 'Excitement Builders', text: "Giveaway: like the post, follow, tag a friend to win a free product/service." },
  { number: 230, bucket: 'SELL', sub_category: 'Excitement Builders', text: "Giveaway: anyone who buys during a specific period enters to win a special bonus." },
  { number: 231, bucket: 'SELL', sub_category: 'Excitement Builders', text: "Sweepstake: buy during a time period to enter for a high-value grand prize." },
  { number: 232, bucket: 'SELL', sub_category: 'Excitement Builders', text: "Low-cost product as a free bonus for limited-time purchase." },
  { number: 233, bucket: 'SELL', sub_category: 'Excitement Builders', text: "5/10/30-day challenge related to your product. Encourage a new habit. Optional discount during." },
  { number: 234, bucket: 'SELL', sub_category: 'Excitement Builders', text: "Ask audience to guess about your upcoming product. 3 hints. Giveaway entry for guessing correctly." },
  { number: 235, bucket: 'SELL', sub_category: 'Excitement Builders', text: "What feedback have you received about a new offer so far?" },
  { number: 236, bucket: 'SELL', sub_category: 'Excitement Builders', text: "What's a small \"secret\" piece of insight you could give to your audience?" },

  // SELL - FAQs
  { number: 237, bucket: 'SELL', sub_category: 'FAQs', text: "What objections do clients most often come to you with?" },
  { number: 238, bucket: 'SELL', sub_category: 'FAQs', text: "What money-related excuses do clients make? How do you make it affordable or risk-free?" },
  { number: 239, bucket: 'SELL', sub_category: 'FAQs', text: "What time-related excuses do clients make? How can you show feasibility?" },
  { number: 240, bucket: 'SELL', sub_category: 'FAQs', text: "What ease-related excuses do clients make? How is it easier than they expect?" },
  { number: 241, bucket: 'SELL', sub_category: 'FAQs', text: "Any other hesitations? How can you put them to rest?" },
  { number: 242, bucket: 'SELL', sub_category: 'FAQs', text: "In what ways do people tell themselves they are not ready?" },
  { number: 243, bucket: 'SELL', sub_category: 'FAQs', text: "What limiting beliefs do people have about themselves?" },
  { number: 244, bucket: 'SELL', sub_category: 'FAQs', text: "What do they think is possible?" },
  { number: 245, bucket: 'SELL', sub_category: 'FAQs', text: "What possibilities do you see for them that they don't yet see for themselves?" },
  { number: 246, bucket: 'SELL', sub_category: 'FAQs', text: "Does your offer include any guarantees?" },
];
