#!/bin/bash
# Solo OS one-time setup. Run this once after `git clone`.
#
# What it does:
#   1. Installs npm dependencies in server/, frontend/, claude-bridge/
#   2. Verifies the `claude` CLI is installed + authenticated
#   3. Builds a `Solo OS.app` bundle in /Applications/ with a custom icon
#      that wraps start-local.sh, so the user can double-click to launch
#      the dashboard like any other Mac app
#
# After this runs once, the user opens Solo OS from /Applications/ (or
# Spotlight, or the Dock if they pin it). No terminal involved.

set -e

DASH_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_NAME="Solo OS"
APP_BUNDLE="/Applications/${APP_NAME}.app"

echo ""
echo "Solo OS setup"
echo "============="
echo ""
echo "Dashboard repo: $DASH_DIR"
echo ""

# ─── 1. npm install in all three subfolders ────────────────────────────────

for sub in server frontend claude-bridge; do
  echo "→ npm install in $sub/"
  (cd "$DASH_DIR/$sub" && npm install --silent --no-audit --no-fund 2>&1 | tail -5)
done

echo ""
echo "✓ Dependencies installed."
echo ""

# ─── 2. Check `claude` CLI ─────────────────────────────────────────────────

if ! command -v claude >/dev/null 2>&1; then
  echo "⚠  The 'claude' CLI is not installed."
  echo ""
  echo "   The dashboard uses your Claude Code subscription for AI features."
  echo "   Install Claude Code from: https://claude.com/code"
  echo ""
  echo "   Once installed, run:  claude auth login"
  echo "   Then re-run:          ./setup.sh"
  echo ""
  exit 1
fi
echo "✓ Found 'claude' at $(command -v claude)"

# Best-effort auth check. `claude` doesn't expose a clean "am I logged in"
# command, but most failures point at auth. Give the user the heads-up.
echo ""
echo "Note: if you have not yet run 'claude auth login', do that now (browser flow)."
echo "Without it the dashboard's AI features will silently fail."
echo ""

# ─── 3. Build the macOS .app bundle ────────────────────────────────────────

echo "→ Building ${APP_NAME}.app at ${APP_BUNDLE}"

# Wipe any prior install
if [ -d "$APP_BUNDLE" ]; then
  rm -rf "$APP_BUNDLE"
fi

mkdir -p "$APP_BUNDLE/Contents/MacOS"
mkdir -p "$APP_BUNDLE/Contents/Resources"

# Copy bundled icon (shipped in the repo at AppIcon.icns)
if [ -f "$DASH_DIR/AppIcon.icns" ]; then
  cp "$DASH_DIR/AppIcon.icns" "$APP_BUNDLE/Contents/Resources/AppIcon.icns"
else
  echo "⚠  AppIcon.icns not found in repo, app will have a default icon"
fi

# Info.plist
cat > "$APP_BUNDLE/Contents/Info.plist" <<'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleIdentifier</key>
  <string>com.solo-os.dashboard</string>
  <key>CFBundleName</key>
  <string>Solo OS</string>
  <key>CFBundleDisplayName</key>
  <string>Solo OS</string>
  <key>CFBundleExecutable</key>
  <string>launcher</string>
  <key>CFBundleIconFile</key>
  <string>AppIcon</string>
  <key>CFBundlePackageType</key>
  <string>APPL</string>
  <key>CFBundleShortVersionString</key>
  <string>0.1.0</string>
  <key>CFBundleVersion</key>
  <string>1</string>
  <key>LSMinimumSystemVersion</key>
  <string>11.0</string>
  <key>NSHighResolutionCapable</key>
  <true/>
  <key>LSUIElement</key>
  <false/>
</dict>
</plist>
PLIST

# Launcher executable - the script that runs when the user double-clicks
# the .app. Writes the absolute path to the cloned repo so the launcher
# always knows where start-local.sh lives.
cat > "$APP_BUNDLE/Contents/MacOS/launcher" <<LAUNCHER
#!/bin/bash
# Solo OS launcher - generated by setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Repo: $DASH_DIR

DASH_DIR="$DASH_DIR"
LOG_DIR="/tmp"

# Ensure node is findable when launched via Finder (no shell init).
# Pick the newest installed nvm version dynamically + cover both Homebrew
# prefixes (Apple Silicon /opt/homebrew, Intel /usr/local).
NVM_BIN=""
if [ -d "\$HOME/.nvm/versions/node" ]; then
  NVM_BIN=\$(ls -d "\$HOME"/.nvm/versions/node/v*/bin 2>/dev/null | sort -V | tail -1)
fi
export PATH="\${NVM_BIN:+\$NVM_BIN:}/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:\$PATH"

# Check if the dashboard is already running. If yes, just open the browser.
if lsof -ti:5174 >/dev/null 2>&1; then
  open -a "Google Chrome" http://localhost:5174 2>/dev/null || open http://localhost:5174
  exit 0
fi

# Start the services in the background via the supervised launcher.
# Invoke through /bin/bash explicitly so macOS provenance (com.apple.provenance
# xattr on cloned/downloaded files) doesn't block exec from the .app bundle.
# Detach via nohup so the .app process can exit cleanly.
nohup /bin/bash "\$DASH_DIR/start-local.sh" > "\$LOG_DIR/solo-os-launcher.log" 2>&1 &

# Wait up to 30 seconds for the frontend to come up, then open browser.
for i in {1..30}; do
  if lsof -ti:5174 >/dev/null 2>&1; then
    sleep 1  # tiny grace period for Vite to actually serve
    open -a "Google Chrome" http://localhost:5174 2>/dev/null || open http://localhost:5174
    exit 0
  fi
  sleep 1
done

# If we got here, services didn't come up in time. Open the log so the
# user can see what failed.
osascript -e "display alert \"Solo OS\" message \"Services did not start in time. Check /tmp/solo-os-launcher.log\""
exit 1
LAUNCHER

chmod +x "$APP_BUNDLE/Contents/MacOS/launcher"

# Force macOS to refresh the icon cache so the new icon shows up
touch "$APP_BUNDLE"

echo "✓ Built ${APP_BUNDLE}"
echo ""

# ─── 4. Done ───────────────────────────────────────────────────────────────

echo "─────────────────────────────────────────────"
echo ""
echo "  ✓ Solo OS is installed."
echo ""
echo "  → Open it from /Applications/Solo OS"
echo "  → Or hit ⌘-Space and type 'Solo OS'"
echo "  → Or drag it to your Dock"
echo ""
echo "  First launch:"
echo "    1. Double-click Solo OS"
echo "    2. Wait ~10 seconds for services to start"
echo "    3. Browser opens to http://localhost:5174"
echo "    4. Password: dev"
echo "    5. Drop your 6 core_*.md files into your vault's 01_Core/"
echo "       folder, then open the dashboard. Extraction auto-runs."
echo ""
echo "  Default vault: $DASH_DIR/sample-vault"
echo "  To point at your own vault, edit start-local.sh and set VAULT_ROOT,"
echo "  or set VAULT_ROOT in your shell before launching."
echo ""
echo "─────────────────────────────────────────────"
echo ""
